name = "DecisionMakingPolicies"
uuid = "4cd5d487-2a85-4602-baee-1f5c94b6a44c"
authors = ["Scott Jordan"]
version = "0.1.0"

[deps]
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DistributionsAD = "ced4e74d-a319-5a8a-b0ac-84af2272839c"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
ChainRulesCore = "1"
ChainRulesTestUtils = "1"
Distributions = "0.23, 0.24, 0.25"
DistributionsAD = "0.6"
Flux = "0.13"
SafeTestsets = "0.1"
Zygote = "0.5, 0.6"
julia = "1.8"

[extras]
ChainRulesTestUtils = "cdddcdb0-9152-4a09-a978-84456f9df70a"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "SafeTestsets", "ChainRulesTestUtils"]
